version: 0.2
phases:
    install:
        runtime-versions:
            java: corretto11
            python: 3.7
    pre_build:
        commands:
            - apt-get update
            - apt-get install -y jq
            - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            - unzip ./sonar-scanner-cli-4.7.0.2747-linux.zip
            - export PATH=$PATH:./sonar-scanner-4.7.0.2747-linux/bin/
    build:
        commands:
            - sonar-scanner -Dsonar.login=5eefd53855316407ac2f50d231e0cf654fdfc932 -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=abhishekmalik2903 -Dsonar.organization=abhishekmalik2903 -DgeneratePom=true
            - sleep 5
            - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=abhishekmalik2903 >result.json
            - cat result.json
            - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi